# Generated by Django 2.1 on 2018-08-24 10:46

from django.db import migrations

def create_initial_topics(apps, schema_editor):
    Topic = apps.get_model('topic', 'Topic')

    Topic(topic_name='Data Type').save()
    Topic(topic_name='String').save()
    Topic(topic_name='Array').save()
    Topic(topic_name='Loop').save()
    Topic(topic_name='Condition').save()
    Topic(topic_name='Data Structure').save()
    Topic(topic_name='Algotithm').save()

class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_topics),
    ]
