# Generated by Django 2.1 on 2018-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topiclevel_outcome'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='topics',
            field=models.ManyToManyField(to='topics.TopicLevel'),
        ),
    ]
