# Generated by Django 2.1.1 on 2018-09-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_description'),
        ('tasks', '0002_task_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='topics',
        ),
        migrations.AddField(
            model_name='task',
            name='main_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_topic+', to='topics.TopicLevel'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='secondary_topics',
            field=models.ManyToManyField(related_name='_task_secondary_topics_+', to='topics.TopicLevel'),
        ),
    ]
