# Generated by Django 2.1.1 on 2018-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180928_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='default_code',
            field=models.TextField(default=''),
        ),
    ]
