# Generated by Django 2.1 on 2018-08-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topiclevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topiclevel',
            options={'ordering': ('topic', 'level')},
        ),
    ]
