# Generated by Django 2.1 on 2018-08-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20180830_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiclevel',
            old_name='standard_score',
            new_name='expected_tasks',
        ),
    ]
