# Generated by Django 2.1 on 2018-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180830_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclevel',
            name='outcome',
            field=models.TextField(blank=True),
        ),
    ]
