# Generated by Django 2.1.1 on 2018-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
