# Generated by Django 2.1.4 on 2018-12-19 20:44

from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_level_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=topics.models._get_image_topic),
        ),
    ]
