# Generated by Django 2.1.4 on 2018-12-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiclevel',
            name='expected_tasks',
        ),
        migrations.RemoveField(
            model_name='topiclevel',
            name='outcome',
        ),
    ]
