# Generated by Django 2.1.2 on 2018-10-30 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0002_auto_20180928_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vote_type', models.CharField(choices=[('best_practice', 'ยอดเยี่ยม'), ('clever', 'ฉลาดใช้')], default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Answer'),
        ),
        migrations.AddField(
            model_name='solutionvote',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
