# Generated by Django 2.1.1 on 2018-09-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_facebook_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='facebook_token',
            new_name='facebook_id',
        ),
    ]
