# Generated by Django 2.1.2 on 2018-10-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180911_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(default='', max_length=140),
        ),
    ]
